Implements #162
cs481-ekh/s23-wildfire-wizards pull request #181
Opened 2023-04-26 19:03 UTC by ethanraygor

2023-04-26 19:19 UTC, ParkerBalbach approved these changes

2023-04-27 04:56 UTC, sawyerball requested changes
![image](https://user-images.githubusercontent.com/77184074/234762830-080d6a36-a286-432d-adf9-6d942d0f7740.png)

Right now when I try to see the fire details, this message pops up in the console. The additional details are not loading at all because of it. It appears to be doing it on every fire.

2023-04-27 05:01 UTC, sawyerball commented
It looks like it is expecting an int somewhere but isn't getting one and so it just crashes.

2023-05-09 02:30 UTC, sawyerball approved these changes

2023-05-09 02:30 UTC, merged