Add new columns to database
cs481-ekh/s23-wildfire-wizards pull request #66
Opened 2023-03-02 19:13 UTC by sawyerball

2023-03-02 20:18 UTC, ParkerBalbach approved these changes

2023-03-05 21:25 UTC, ethanraygor requested changes
I fixed the test cases so you should be able to merge main into this branch to make sure these changes can pass the test cases.

2023-03-06 20:54 UTC, sawyerball commented
I merged main into this branch so it now passes the checks.

2023-03-06 20:54 UTC, ethanraygor approved these changes
Looks good!

2023-03-06 21:37 UTC, merged